### ISSUE TITLE
beautify the team section

### ISSUE THREAD

**Issue by championshuttler** [Moz-NIEC/moz-hack-3#33]

**Comment by suhailsinghbains** [comment]
What should it be like? Any ideas in mind?

**Comment by akshat0047** [comment]
Taking up this issue if its not already being worked upon will show mock soon

**Comment by akshat0047** [comment]
![ss](https://user-images.githubusercontent.com/32462195/45517421-b653f600-b7cb-11e8-949a-1a48ebf5b30a.png)

will something like this work good, adding a slick carousel or slideshow with intro animation as flipping down the tiles would look good, should I go for it?

**Comment by championshuttler** [comment]
Hi @akshat0047 , yeah its looking good + we can do something like add little bio and social media links to the profile of the people in team section. How does it sound to you?

**Comment by akshat0047** [comment]
Yeah it'll be great. I have left that space for the same, will do it asap @championshuttler

**Comment by championshuttler** [comment]
@suhailsinghbains can you please take a look into it and provide all necessary links to @akshat0047 . @akshat0047 i think we can use # as `href` for now , we can add it later :)

**Comment by akshat0047** [comment]
yes, sure.

**Comment by suhailsinghbains** [comment]
> 
> 
> @suhailsinghbains can you please take a look into it and provide all necessary links to @akshat0047 . @akshat0047 i think we can use # as `href` for now , we can add it later :)

Yeah, sure, sending the links right away !

**Comment by suhailsinghbains** [comment]
Shivam Singhal 
https://mozillians.org/en-US/u/championshuttler/
https://github.com/championshuttler/
https://reps.mozilla.org/u/championshuttler/
https://telegram.me/championshuttler

Suhail Singh Bains
https://mozillians.org/en-US/u/suhailsinghbains/
https://github.com/suhailsinghbains
www.linkedin.com/in/suhailsinghbains
https://telegram.me/suhailsinghbains

Rishabh Bansal
https://github.com/rishabh-bansal
https://mozillians.org/en-US/u/rishabhbansal/
https://githubcampus.expert/rishabh-bansal/

**Comment by suhailsinghbains** [comment]
Add icons to make the page beautiful & hide the links completely for a simple word

**Comment by suhailsinghbains** [comment]
> 
> 
> Add icons to make the page beautiful & hide the links completely for a simple word

Sorry, didn't see the PR before this comment, please ignore this.

**Comment by akshat0047** [comment]
@suhailsinghbains 
Shivam Singhal - facebook link, also should I use mozillian or mozilla-reps link
Rishabh Bansal - facebook link, telegram link, also should I use github or github-expert link

-Bio for all team members
-The icons for mozilla reps and github expert are not specifically available

**Comment by championshuttler** [comment]
@akshat0047 relax leave them , just use normal public profile you have no need to worry about mozillians or github expert stuff :)

Relax

**Comment by suhailsinghbains** [comment]
Shivam Singhal - Facebook link<https://www.facebook.com/championshuttler> use mozillian, as it has more content :)
Rishabh Bansal - Facebook link<https://www.facebook.com/rishabhbansal97> use github and github-expert as I cannot find his telegram :)

Shivam's Bio -> Developer | Night Owl | Food Hogger ¯\_(ツ)_/¯ 
Suhail's Bio -> Love Chay
Regarding Bansal's Bio, will update you soon for that

**Comment by akshat0047** [comment]
updated, also, according to the dates the hackathon is on 29 and 30 september 2018, is the event postponed or the website will be under development for some other purpose?
