### ISSUE TITLE
Add smooth scroll to nav-tabs

### ISSUE THREAD

**Issue by akshat0047** [Moz-NIEC/moz-hack-3#48]
The tabs in the navbar are spawning the view to specified section instead it should scroll smoothly to the location.

**Comment by championshuttler** [comment]
Yeah , thanks for creating a issue @akshat0047  , would you like to work on it  ? Happy to help if you need

**Comment by akshat0047** [comment]
Yes I'll work on it.

**Comment by championshuttler** [comment]
Great , go ahead please :)
